const regexr = {
    city: /^[A-Za-záÁéÉíÍóÓúÚñÑ ]{5,30}$/,
    schoolType: /^[A-Za-záÁéÉíÍóÓúÚñÑ ]{5,30}$/,
    checkOutType: /^(staff|vehicular)$/,
    status: /^(programmed|initiated|finalized|canceled|incomplete)$/,
    type: /^(staff|vehicular)$/,
    staffId:/^[0-9]{1,}$/,
    vehicleId:/^[0-9]{1,}$/,
    deparment: /^[A-Za-záÁéÉíÍóÓúÚñÑ ]{5,40}$/,
    firstname: /^[A-Za-záÁéÉíÍóÓúÚñÑ ]{3,40}$/,
    lastname: /^[A-Za-záÁéÉíÍóÓúÚñÑ ]{3,40}$/,
    email: /^[a-zA-Z0-9._-]{3,50}@[a-zA-Z-0-9]{1,40}\.[a-zA-Z-0-9]{2,10}(.mx)?$/,
    password: /^.{1,100}$/,
    vehicle: /^[A-Za-z0-9áÁéÉíÍóÓúÚñÑ\- ]{10,35}$/,
    destination: /^[A-Za-z0-9áÁéÉíÍóÓúÚñÑ\s ]{4,50}$/,
    outletTankLavel: /^[A-Za-z0-9 íÍ/]{3,10}$/,
    reason: /^[A-Za-z0-9áÁéÉíÍóÓúÚñÑ\s. ]{4,50}$/,
    vehicleName: /^[A-Za-z0-9áÁéÉíÍóÓúÚñÑ ]{3,40}$/,
    initMileage:/^[0-9]{1,6}$/,
    initTankLavel:/^[A-Za-z0-9 íÍ/]{3,10}$/,
    campId: /^[0-9]{1,}$/,
    id: /^[0-9]{1,}$/,
    deparmentId: /^[0-9]{1,}$/,
    checkOutId: /^[0-9]{1,}$/,
    arrivalKm:/^[0-9]{1,6}$/,
    inputTankLavel:/^[A-Za-z0-9 íÍ/]{3,10}$/,
    initialDate: /^[0-9/]{10}$/,
    finalDate: /^[0-9/]{10}$/,
    own: /^[A-Za-záÁéÉíÍóÓúÚñÑ ]{3,50}$/,
    fixedAssetType: /^[0-9A-Za-záÁéÉíÍóÓúÚñÑ ]{3,50}$/,
    articleName: /^[0-9A-Za-záÁéÉíÍóÓúÚñÑ ]{3,50}$/,
    clasification: /^[0-9A-Za-záÁéÉíÍóÓúÚñÑ.,:/_ -]{3,40}$/,
    brand: /^[0-9A-Za-záÁéÉíÍóÓúÚñÑ.,:/_ -]{2,40}$/,
    model: /^[0-9A-Za-záÁéÉíÍóÓúÚñÑ.,:/_ -]{2,40}$/,
    state: /^Nuevo|Regular|Bueno$/,
    departmentId: /^[0-9]{1,}$/,
    quantity: /^[0-9]{1,9}$/,
    inCharge:/^[0-9,]{1,}$/,
    features:/^[0-9.a-zA-ZáÁéÉíÍóÓúÚñÑ, '_-]{3,200}$/,
    observations: /^[0-9A-Za-záÁéÉíÍóÓúÚñÑ ]{5,150}$/,
    monthAndYear: /^[0-9/]{7}$/,
    inventoryType:/^department|employee$/,
    offset:/^[0-9]{1,}$/,
    page:/^[0-9]{1,}$/,
    employeeId: /^[0-9]{1,}$/,
    equipmentId: /^[0-9]{1,}$/,
    removeImage: /^true|false$/,
    bill: /^[0-9/]{5,10}$/,
    unit: /^PIEZA|PAQUETE|CAJA|BLOCK|TIRAS$/,
}

module.exports = regexr;